# Import library

In [3]:
import pandas as pd
import numpy as np

# Code

In [6]:
df = pd.read_csv("C:/Users/basisdata/Downloads/Data BPJS 2019.csv", index_col=[0])
df.head()

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,157978748.0,50765420,20.064983,958073632,2019-08-01,2019-08-01,61,6108,3,1,...,9999,9999,98,9998,98,98,98,98,2,Sehat
1,95085112.0,26931775,2.626307,449590620P000054,2020-06-17,2020-06-17,51,5171,9,3,...,K297,"Gastritis, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
2,224470578.0,227368233,1.051830,467490619P000001,2019-06-01,2019-06-01,35,3516,9,2,...,Z309,"Contraceptive management, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
3,63871289.0,62313678,364.741455,254321219Y002368,2019-12-21,2019-12-21,34,3402,3,1,...,I10,Essential (primary) hypertension,98,9998,98,98,98,98,1,Belum_Sehat
4,29915626.0,113446188,1.050523,88681119P000020,2019-11-04,2019-11-04,35,3509,3,1,...,I110,Hypertensive heart disease with (congestive) h...,98,9998,98,98,98,98,1,Belum_Sehat

In [7]:
print("Data diatas memiliki {} baris dan {} kolom".format(df.shape[0],df.shape[1]))

Data diatas memiliki 500000 baris dan 26 kolom

In [8]:
# Mengubah tipe kolom tanggal datang dan pulang ke pd datetime
df["Tanggal datang kunjungan FKTP"] = pd.to_datetime(df["Tanggal datang kunjungan FKTP"])
df["Tanggal pulang kunjungan FKTP"] = pd.to_datetime(df["Tanggal pulang kunjungan FKTP"])

df["Tahun datang"] = df["Tanggal datang kunjungan FKTP"].dt.year
df["Bulan datang"] = df["Tanggal datang kunjungan FKTP"].dt.month
df["Tanggal datang"] = df["Tanggal datang kunjungan FKTP"].dt.day

df["Tahun pulang"] = df["Tanggal pulang kunjungan FKTP"].dt.year
df["Bulan pulang"] = df["Tanggal pulang kunjungan FKTP"].dt.month
df["Tanggal pulang"] = df["Tanggal pulang kunjungan FKTP"].dt.day

df

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta,Tahun datang,Bulan datang,Tanggal datang,Tahun pulang,Bulan pulang,Tanggal pulang
0,157978748.0,50765420,20.064983,958073632,2019-08-01,2019-08-01,61,6108,3,1,...,98,98,2,Sehat,2019,8,1,2019,8,1
1,95085112.0,26931775,2.626307,449590620P000054,2020-06-17,2020-06-17,51,5171,9,3,...,98,98,1,Belum_Sehat,2020,6,17,2020,6,17
2,224470578.0,227368233,1.051830,467490619P000001,2019-06-01,2019-06-01,35,3516,9,2,...,98,98,1,Belum_Sehat,2019,6,1,2019,6,1
3,63871289.0,62313678,364.741455,254321219Y002368,2019-12-21,2019-12-21,34,3402,3,1,...,98,98,1,Belum_Sehat,2019,12,21,2019,12,21
4,29915626.0,113446188,1.050523,88681119P000020,2019-11-04,2019-11-04,35,3509,3,1,...,98,98,1,Belum_Sehat,2019,11,4,2019,11,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,52248195.0,99457992,442.270020,58190419Y006723,2019-04-26,2019-04-26,14,1405,9,2,...,98,98,1,Belum_Sehat,2019,4,26,2019,4,26
499996,100074300.0,151146239,59.774738,276060720P000131,2020-07-15,2020-07-15,73,7310,3,1,...,28,99,1,Belum_Sehat,2020,7,15,2020,7,15
499997,95115654.0,95115654,155.687454,210781019P000426,2019-10-09,2019-10-09,12,1275,8,2,...,98,98,1,Belum_Sehat,2019,10,9,2019,10,9
499998,100522053.0,100522053,51.685715,167730919P000325,2019-09-20,2019-09-20,32,3212,3,1,...,98,98,1,Belum_Sehat,2019,9,20,2019,9,20
499999,94310305.0,127908459,83.201393,401411119P000296,2019-11-22,2019-11-22,32,3205,3,1,...,98,98,1,Belum_Sehat,2019,11,22,2019,11,22

In [9]:
# Mengganti kolom kelas str menjadi numeric
df['Status'] = df ["Kelas Status Pulang Peserta"].map({"Sehat" : 1, "Belum_Sehat":0})
df

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta,Tahun datang,Bulan datang,Tanggal datang,Tahun pulang,Bulan pulang,Tanggal pulang,Status
0,157978748.0,50765420,20.064983,958073632,2019-08-01,2019-08-01,61,6108,3,1,...,98,2,Sehat,2019,8,1,2019,8,1,1
1,95085112.0,26931775,2.626307,449590620P000054,2020-06-17,2020-06-17,51,5171,9,3,...,98,1,Belum_Sehat,2020,6,17,2020,6,17,0
2,224470578.0,227368233,1.051830,467490619P000001,2019-06-01,2019-06-01,35,3516,9,2,...,98,1,Belum_Sehat,2019,6,1,2019,6,1,0
3,63871289.0,62313678,364.741455,254321219Y002368,2019-12-21,2019-12-21,34,3402,3,1,...,98,1,Belum_Sehat,2019,12,21,2019,12,21,0
4,29915626.0,113446188,1.050523,88681119P000020,2019-11-04,2019-11-04,35,3509,3,1,...,98,1,Belum_Sehat,2019,11,4,2019,11,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,52248195.0,99457992,442.270020,58190419Y006723,2019-04-26,2019-04-26,14,1405,9,2,...,98,1,Belum_Sehat,2019,4,26,2019,4,26,0
499996,100074300.0,151146239,59.774738,276060720P000131,2020-07-15,2020-07-15,73,7310,3,1,...,99,1,Belum_Sehat,2020,7,15,2020,7,15,0
499997,95115654.0,95115654,155.687454,210781019P000426,2019-10-09,2019-10-09,12,1275,8,2,...,98,1,Belum_Sehat,2019,10,9,2019,10,9,0
499998,100522053.0,100522053,51.685715,167730919P000325,2019-09-20,2019-09-20,32,3212,3,1,...,98,1,Belum_Sehat,2019,9,20,2019,9,20,0
499999,94310305.0,127908459,83.201393,401411119P000296,2019-11-22,2019-11-22,32,3205,3,1,...,98,1,Belum_Sehat,2019,11,22,2019,11,22,0

In [ ]:
tahun = [2019,2019,2020,2021]

In [16]:
# Fungsi missing check
def missing_check(df) :
    missing = df.isnull().sum()
    per_miss = missing/len(df)
    data_type = df.dtypes
    number_unique = df.nunique()
    return pd.DataFrame({"Missing":missing,
                        "Percent_Missing":per_miss,
                       "Data_Types": data_type,
                        "Number_of_unique":number_unique}).style.format({'Percent_Missing' : "{:.2%}"})

In [17]:
missing_check(df)